version: '3'

services:
  leetcode-lite:
    container_name: leetcode-lite
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5433"
    command: "-p 5433"